# 定数ファイル(API用)


# レスポンスコード
class RESPONSE_CODE:
    SUCCESS = "0000"
    NOT_FOUND = "I001"
    INTERNAL_SERVER_ERROR = "E000"
    AUTH_ERROR = "E001"
    DB_ERROR = "E002"
    FILE_IMPORT_ERROR = "E003"
    VALIDATION_ERROR = "E004"
    SPOTIFY_ERROR = "E005"
    UNKNOWN_ERROR = "E999"
