name: BAT000002_API定期実行バッチ
on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:
jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: A000001_ヘルスチェックAPI
        run: |
          curl -X GET "https://skotune-ai-api.onrender.com/api/v1/health" \
               -H "Content-Type: application/json"
